spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.79:3306/demo?characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: dimine2022
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
      initial-size: 10
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      validation-query: SELECT 1 FROM DUAL
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
    # 生产环境一定要关闭
    clean-disabled: true
